### ISSUE TITLE
Crash "kill ESRCH"

### ISSUE THREAD

**Issue by hitl0r** [pwnsdx/RandomDNS#6]
After approx. half a day RandomDNS crashes with error: (with DEBUG)

```
NOTICE] Proxying from 127.0.0.2:53 to 173.234.56.115:443 +1ms
node.js:748
        throw errnoException(err, 'kill');
        ^

Error: kill ESRCH
    at exports._errnoException (util.js:890:11)
    at process.kill (node.js:748:15)
    at null._onTimeout (/home/randomdns/.linuxbrew/lib/node_modules/randomdns/run.js:298:25)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

**Comment by pwnsdx** [comment]
Thanks for reporting this issue. It seems that node tried to kill the process twice. I'll look into it.

**Comment by hitl0r** [comment]
Thanks - if it helps: this happend 3 times now, always after maybe around 12-16 hours of runtime

**Comment by hitl0r** [comment]
I started node with
`--max-old-space-size=1024`

so far it is running for > 24 hours. I will keep you updated, no idea if this is really helpful.
Found this here 
https://github.com/nodejs/node/issues/2738 
for garbage collection /memory issues.

**Comment by hitl0r** [comment]
Same process still running today - I think it helped

**Comment by pwnsdx** [comment]
Hello,

Had an uptime of more than 4 days but I got the same issue today. It was because of a connectivity issue, I think it's because a dnscrypt process die before RandomDNS kill it to rotate the server. I'm just going to add a workaround for the moment.

Thanks!
S.
